# Generated by Django 3.1.1 on 2020-09-22 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
