# Generated by Django 3.1.1 on 2020-09-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_data_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
